name: Build Scripts

on:
    workflow_dispatch: null
    push:
        paths:
            - scripts

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build
              run: |
                  yarn
                  yarn build-script
                  yarn build-bookmarklet
            - name: Upload
              run: |
                  git switch --orphan gh-pages
                  mv scripts/generated/*.js .
                  git add *.js
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git commit -m Build
                  git push origin gh-pages -f
